- common/tasks/rosa/hosted-cp/rosa-hcp-deprovision/rosa-hcp-deprovision.yaml
Testing a fix for failing ci, theory is that having description underneath steps is problematic.
> remove descriptions

- common/tasks/quality-dashboard/quality-dashboard-upload.yaml
Jira: [KONFLUX-3458](https://issues.redhat.com/browse/KONFLUX-3458)
Add a task for sending metrics from Konflux to a new [quality-dashboard endpoint](https://github.com/konflux-ci/quality-dashboard/pull/332)
> feat: add quality-dashboard-upload task

- common/tasks/test-metadata/0.1/test-metadata.yaml
> Add source repo and source branch

- common/tasks/rosa/hosted-cp/rosa-hcp-provision/rosa-hcp-provision.yaml
Reverts konflux-ci/konflux-qe-definitions#59
> Revert "fix a minor issue of rosa provision"

- common/tasks/rosa/hosted-cp/rosa-hcp-provision/rosa-hcp-provision.yaml
- common/tasks/sprayproxy/sprayproxy-deprovision/sprayproxy-unregister-server.yaml
fix the issue of unregistering pcs server. It shouldn't delete all of PAC servers
> fix the issue of unregistering pcs server

- scripts/rosa/delete-rosa-clusters.sh
https://issues.redhat.com/browse/KFLUXDP-7
tested via prow job: 
https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/openshift_release/57763/rehearse-57763-periodic-ci-konflux-ci-e2e-tests-main-rosa-old-clusters-cleanup/1846235122341253120
> fix: delete clusters including related subnet tags

- dockerfiles/tool-box/Dockerfile
> feat(KFLUXDP-104): Add cosign to inspect konflux ci build images

- docs/SUMMARY.md
- docs/qe-available-tasks/sealights/go-instrumentation/go-instrumentation.md
- tasks/sealights/sealights-go-instrumentation/0.1/README.md
- tasks/sealights/sealights-go-instrumentation/0.1/sealights-go-instrumentation.yaml
This pull request adds a new Tekton task that makes it easier to instrument Go code with Sealights for quality analytics. The task automates retrieving the source code, running the Sealights instrumentation, and creating a new trusted artifact with the instrumented code.
A README file is included with clear instructions and an example pipeline to help you get started quickly
> feat(KFLUXDP-99): Add Tekton task that instrument Golang source code with sealights agents

- scripts/rosa/delete-rosa-clusters.sh
rosa delete command never deletes the TG. With this changes will delete all TG that are older than 24 in periodic jobs
> feat: Delete all target groups that are older than 24h instead of deleting by undeleted LB

- scripts/rosa/delete-rosa-clusters.sh
https://github.com/konflux-ci/tekton-integration-catalog/pull/89#discussion_r1916183552
> fix: follow-up on #89

- docs/SUMMARY.md
- docs/qe-available-tasks/sealights/nodejs-instrumentation/0.1-nodejs-instrumentation.md
- tasks/sealights/sealights-nodejs/0.1/README.md
- tasks/sealights/sealights-nodejs/0.1/sealights-nodejs.yaml
Tested with
* [backend application](https://github.com/psturc/nodejs-sl-test/commit/ad807d74bdc7035c0cccfdac9001aa2af74e52ac)
* [frontend application](https://github.com/psturc/nodejs-sl-test/commit/4f3f19229af611ae9dabcebc80883eb109ba0a28)
> feat: Node.js instrumentation task

- scripts/rosa/delete-rosa-clusters.sh
Due to https://issues.redhat.com/browse/OHSS-41374
> Increase rosa-delete timeout

- konflux/sealights-agents/go/Dockerfile
> update sealights go agent to 1.1.184

- scripts/integration-tests-scheduler/integration-tests-scheduler.sh
Im adding this script here due I dont find a better place. In the end is responsible to trigger Integration Tests and most of those tasks are related with this catalog
> feat: creates scripts that manage to trigger integration tests

- stepactions/bundles/get-unreleased-bundle/0.1/get-unreleased-bundle.yaml
- stepactions/bundles/pick-cluster-arch/0.1/pick-cluster-arch.yaml
* removed new line characters from a string ` echo -n -e "$highest_version_from_bundles_list"`
* changed a few return codes
> feat: remove new line character from a string

- tasks/sealights/sealights-get-refs/0.1/sealights-get-refs.yaml
https://issues.redhat.com/browse/KFLUXDP-270
> fix: extract image ref using IMAGE param

- tasks/store-pipeline-status/0.1/README.md
- tasks/store-pipeline-status/0.1/store-pipeline-status.yaml
https://issues.redhat.com/browse/KFLUXDP-238
* [Example of such report](https://app-artifact-browser.apps.rosa.konflux-qe.zmr9.p3.openshiftapps.com/e2e-tests/konflux-e2e-8fh57/pipeline-status.json)
> feat: task to gather and store pipelinerun status

- tasks/store-pipeline-status/0.1/store-pipeline-status.yaml
In order to collect data with quality dashboard:
* We need to assign a test scenario and event to the pipeline status to appear in the dashboard
* Relate git org and repo
> feat(KFLUXDP-240): Add more data to the pipeline status colletor

- pipelines/deploy-fbc-operator/0.1/README.MD
- pipelines/deploy-fbc-operator/0.1/deploy-fbc-operator.yaml
> Adding parameter to specify where the imagedigestmirrorset is saved

- konflux/tekton-integration-catalog-utils/tekton-integration-catalog-utils/Dockerfile
> chore: update rosa cli version

- tasks/konflux-ci/deploy/0.3/deploy-konflux-ci.yaml
fixes https://issues.redhat.com/browse/KONFLUX-9267
Verified with [this PR](https://github.com/konflux-ci/release-service/pull/801)
and checking the coverage in SL dashboard after tests were finished
> fix: update component deployment with SL token

- pipelines/deploy-fbc-operator/0.1/deploy-fbc-operator.yaml
to be flexible regarding the location of the image digest mirror set
> OLS-2032 - Modifying retrieve mirror set and scorecard config 

- README.md
- pipelineruns/conforma-with-waiting/0.1/README.MD
- pipelineruns/conforma-with-waiting/0.1/conforma-with-waiting.yaml
* Add pipeline which first waits for all integration tests for the given Snapshot to finish before running the Conforma verify task
> feat(STONEINTG-1297): add conforma-with-waiting pipelineRun

- scripts/mapt/README.md
- scripts/mapt/delete-mapt-clusters.sh
https://issues.redhat.com/browse/KFLUXDP-427
tested with a periodic job created in [this PR](https://github.com/openshift/release/pull/69945)
> feat: cleanup leftovers from mapt created clusters

- .tekton/mapt-provision-test-pull-request.yaml
- tasks/mapt-oci/kind-aws-spot/provision/0.2/Readme.md
Adds mapt provision and deprovision testing when those tasks are modified.
> feat: add mapt provision testing
