konflux-ci/tekton-integration-catalog

common/tasks/rosa/hosted-cp/rosa-hcp-provision/rosa-hcp-provision.yaml

The prevision implementation cannot make sure the required cluster operators are in  ready status, this can solve the issue

reverted check_clusteroperators method back

---

common/tasks/rosa/hosted-cp/rosa-hcp-provision/rosa-hcp-provision.yaml

Sometimes it will fail with the following error, this PR is to make sure it won't break the whole process when api server host somehow is not available  .
```
[provision] INFO: Check if apiserver is ready...
[provision] Retried 1 times...
[provision] Unable to connect to the server: dial tcp: lookup api.kx-4298439a99.i7nt.p3.openshiftapps.com on 172.30.0.10:53: no such host
```

fix a minor issue of rosa provision

---

common/tasks/rosa/hosted-cp/rosa-hcp-deprovision/rosa-hcp-deprovision.yaml

Code requiring these parameters disappeared long time ago: https://github.com/konflux-ci/konflux-qe-definitions/commit/d64b77195f7605d7d48f15458871f6f6f4af0015#diff-0ef56e22bed55502a8f9219c48e9242cbef41f68fac5f22f89d0a5ac5571e81b

Remove unecessary parameters from collect-artifacts-deprovision-rosa

---

common/tasks/test-metadata/0.2/test-metadata.yaml

This is the [PR](https://github.com/konflux-ci/release-service-catalog/pull/657/files)  which is using the "pull-request-author".

fix: change the author in retest for konflux updates prs

---

common/tasks/rosa/hosted-cp/rosa-hcp-deprovision/rosa-hcp-deprovision.yaml
dockerfiles/tool-box/Dockerfile

https://issues.redhat.com/browse/KFLUXDP-6
```bash
➜ podman build -t leaktk-test . -f dockerfiles/tool-box/Dockerfile
➜ podman run -w /tmp leaktk-test bash -c "git clone https://github.com/leaktk/fake-leaks . && leaktk-scanner scan --kind Files --resource . | leaktk-remove-files . && git status"
On branch main
Your branch is up to date with 'origin/main'.
Changes not staged for commit:
(use "git add/rm <file>..." to update what will be committed)
(use "git restore <file>..." to discard changes in working directory)
deleted:    aws
deleted:    containers/container-auth.1.json
deleted:    containers/container-auth.2.json
deleted:    containers/container-auth.3.json
deleted:    dynatrace-token
deleted:    foo.clientSecret
deleted:    foo.p12
deleted:    foo.password
...
```

feat: replace trufflehog with leaktk

---

common/tasks/rosa/hosted-cp/rosa-hcp-deprovision/rosa-hcp-deprovision.yaml
dockerfiles/tool-box/Dockerfile

Our CI does not get triggered on PR/push and `quay.io/konflux-qe-incubator/konflux-qe-tools:latest` image does not get updated, hence this PR needs to be reverted  
Reverts konflux-ci/tekton-integration-catalog#73

Revert "feat: replace trufflehog with leaktk"

---

common/tasks/rosa/hosted-cp/rosa-hcp-deprovision/rosa-hcp-deprovision.yaml
dockerfiles/tool-box/Dockerfile
stepactions/fail-if-any-step-failed/0.1/README.md
stepactions/fail-if-any-step-failed/0.1/fail-if-any-step-failed.yaml
stepactions/secure-push-oci/0.1/README.md
stepactions/secure-push-oci/0.1/secure-push-oci.yaml

https://issues.redhat.com/browse/KFLUXDP-6
This PR introduces 2 new stepactions:
* `secure-push-oci`, that scans the content of the specified directory, removes files that contain leaked information and pushes the directory content to the new/existing OCI artifact in quay.io, including the log from the leaktk CLI scan
* `fail-if-any-step-failed` - which purpose is to exit with non-zero code, if any of the steps executed as a part of the tekton Task exited with non-zero code. This is useful in Tasks, where we want to save artifacts that were produced by a step, where the error was purposely ignored (using `error: continue` field), but still want to fail the Task in the end, to give the user the correct job results
* it also contains a commit from [this …

feat: stepactions for secure push to OCI registry

---

common/tasks/pull-request-comment/0.2/pull-request-comment.yaml

pull-request-status-message task is currently failing with 
```
error requesting remote resource: error getting "Git" "rhtap-shared-team-tenant/git-9e39917f050fbbfe4cb4f9bf932ded92": error opening file "common/stepactions/analyze-test-results/0.1/analyze-test-results.yaml": file does not exist
```
This should hopefully fix it.

Fix analyze-test-results path

---

common/tasks/pull-request-comment/0.1/pull-request-comment.yaml

This PR enables test results analyzer for pipelines that are using Task [test-metadata v0.1](https://github.com/konflux-ci/tekton-integration-catalog/tree/main/common/tasks/test-metadata/0.1)
(it's incompatible with test-metadata v0.2 due to [change of field names in job-spec object](https://github.com/konflux-ci/tekton-integration-catalog/blob/c2cb7ebf64bc6f575ec4536f2b489fb81c2317fa/common/tasks/test-metadata/0.2/test-metadata.yaml#L78-L79) that happened between v0.1 and v0.2 - it was failing on `jq` error)
This PR adds 4 new parameters to the Task, but all of them have default values, plus the test analysis is turned off by default, so it shouldn't impact users that are already using this Task version
Validated in [this PR](https://github.com/konflux-ci/build-service/pull/387#issuecomme …

fix: add analyzer to pull-request-comment v0.1

---

docs/qe-available-tasks/sealights/go-instrumentation/go-instrumentation.md
tasks/sealights/sealights-go-instrumentation/0.1/sealights-go-instrumentation.yaml

Simplify retrieving the event type from task metadata execution, eliminating the need for users to specify the event type via parameters

feat: Get tekton event type from the task metadata labels

---

docs/SUMMARY.md
docs/qe-available-tasks/sealights/python-instrumentation/python-instrumentation.md
tasks/sealights/sealights-python/0.1/README.md
tasks/sealights/sealights-python/0.1/sealights-python.yaml

This pull request adds a new Tekton task that makes it easier to configure Python code with Sealights for quality analytics. It retrieves the source code from a trusted artifact, installs Python Sealights agent, configures the app for sealights using  vars from your pipeline run, scans all .py files that are not in the --exclude step above and reports scan to sealights, and stores results to be used later on in testing.
A README file is included with clear instructions and an example pipeline to help you get started quickly
This was tested using this PR where I created a pipeline for the todo-list python example app and ran robot tests in an integration test scenario
https://github.com/ascerra/todo-list-app/pull/15
- I covered both syntax for when it is a PR and not a PR in the most …

Add Tekton task to configure sealights for Python.

---

common/tasks/test-metadata/0.1/test-metadata.yaml
common/tasks/test-metadata/0.2/test-metadata.yaml
docs/qe-available-tasks/test-metadata/0.1-test-metadata.md
docs/qe-available-tasks/test-metadata/0.2-test-metadata.md

**tl;dr;** This PR introduces new Tekton Result field for `test-metadata` Task: `target-repo-branch`
Regarding branch names we have only `source-repo-branch` in test-metadata task.
That one is not sufficient if user would like to run integration tests on `push` events, because in that case the source branch annotation looks like this:
```
pac.test.appstudio.openshift.io/source-branch: refs/heads/main
```
and it's complicated to use it in this format.
So for that case I thought it'd make sense to extract the value from the following annotation:
```
pac.test.appstudio.openshift.io/branch: main
```
which points to:
* target branch name in case of `pull-request` event
* branch name in case of `push` event
Tested with [my integration pipeline](https://github.com/psturc/nodejs-sl-test/blob/b3645 …

fix: add target-repo-branch to test-metadata Task

---

stepactions/sealights/upload-ginkgo-results/0.1/README.md
stepactions/sealights/upload-ginkgo-results/0.1/upload-ginkgo-results.yaml

This Tekton StepAction uploads Ginkgo test results to Sealights. It creates a Sealights test session,  processes the Ginkgo JSON report, sends the test results to Sealights, and then deletes the test session to clean up resources.
Tested successfully in real app: https://github.com/konflux-ci/build-service/pull/393

feat(140): Add step action that help to upload ginkgo results to Sealights

---

common/tasks/pull-request-comment/0.1/pull-request-comment.yaml

We are using the `pull-request-comment` task as part of the build-definitions build pipeline where `build` or `integration` console urls need to constructed a bit differently than konflux integration test pipeline.

fix: build/integration console urls for build-definitions CI

---

tasks/sealights/sealights-get-refs/0.1/sealights-get-refs.yaml

See pull request https://github.com/konflux-ci/build-definitions/pull/1868

feat(): Adapt get refs sealights task to build-definition tasks that were migrated

---

tasks/sealights/sealights-get-refs/0.1/sealights-get-refs.yaml

Sometimes in TA we are getting the IMAGE_REF duplicated because is pushing the dockerfile as an artifact to quay. This pull request get the image digest and concat with IMAGE_URL which seems more accurate!
```json
{
"name": "CACHI2_ARTIFACT",
"type": "string",
"value": ""
}
{
"name": "SOURCE_ARTIFACT",
"type": "string",
"value": "oci:quay.io/redhat-user-workloads/rhtap-build-tenant/build-service/build-service@sha256:1c566ecc87294c432f6de54e6f900d6bba1be3e5dc267ab373bf02ddb14e9677"
}
{
"name": "IMAGE_DIGEST",
"type": "string",
"value": "sha256:d423b16d84360e2da3daa0cdbbb4d4c9d83a59900416e4f8dae407bea068726f"
}
{
"name": "IMAGE_REF",
"type": "string",
"value": "quay.io/redhat-user-workloads/rhtap-build-tenant/build-service/build-service:on-pr-089213f1a212737f76ff4c7ea5e300d6f1db635f@sha256:d …
```

feat(): Improve how we get the sealights images from a pristine image

---

common/tasks/pull-request-comment/0.1/pull-request-comment.yaml

When using this task in the build-definitions CI, our CI pipeline run status is `Completed` sometimes based on the changes done in the PR, since some tasks are skipped, so it is pipeline run status is marked `Completed`. One such [example](https://github.com/konflux-ci/build-definitions/pull/1890#issuecomment-2630993291) . Changing the check in this task to skip commenting in the PR when the pipeline run status is `Completed` as well.

fix: skip commenting for `Completed` pipeline run status

---

renovate.json

I tested this config with renovate bot enabled in my fork of this repository:
* https://github.com/psturc/tekton-integration-catalog/pull/5
* https://github.com/psturc/tekton-integration-catalog/pull/6

feat: renovate config for slnodejs and sl-python

---

common/tasks/quality-dashboard/0.1/quality-dashboard-upload.yaml

Recently we add reports in json and by default Quality dashboard sends those reports in json format. The dashboard only accept junit format. I change the regex to find only .xml files

fix(KONFLUX-6983): Make quality dashboard to find junit files that ends in .xml format

---

konflux/tekton-integration-catalog-utils/tekton-integration-catalog-utils/Dockerfile

The latest push pipeline failed due to flakey unit leaktk/scanner test:
```
--- FAIL: TestPriorityQueue (0.00s)
--- FAIL: TestPriorityQueue/Send/Recv (0.00s)
priorityqueue_test.go:52: 
Error Trace:	/opt/app-root/src/scanner/pkg/queue/priorityqueue_test.go:52
Error:      	Not equal: 
expected: []string{"A", "B", "C", "D", "E"}
actual  : []string{"E", "A", "B", "C", "D"}
```
I noticed [leaktk/scanner repo started to release built artifacts since v0.0.16](https://github.com/leaktk/scanner/releases/tag/v0.0.16), so I decided to install the `leaktk-scanner` binary directly by pulling it from GitHub

fix: utils image: leaktk installation

---

tasks/test-metadata/0.2/README.md
tasks/test-metadata/0.2/test-metadata.yaml

Added support to the `test-metadata` task to grab the OCI artifact that holds the prefetch dependencies from the build phase.
This allows integration tests to use prefetched dependencies while keeping the default behavior unchanged unless explicitly enabled.

feat(test-metadata): add support for downloading prefetch artifact

---

tasks/test-metadata/0.2/test-metadata.yaml

Tekton supports only strings, arrays, and objects for parameters; boolean values are not allowed. This commit updates the `enable-prefetch` parameter in the `test-metadata` task to use a string instead of a boolean.
Without this change, the task will fail in the webhook admission controller with the error:
`access denied the request: validation failed: invalid value: bool: spec.params.enable-prefetch.type`.

fix(test-metadata): change boolean parameter to string in task

---

common/tasks/rosa/hosted-cp/rosa-hcp-provision/rosa-hcp-provision.yaml
tasks/rosa/hosted-cp/rosa-hcp-provision/0.1/rosa-hcp-provision.yaml
tasks/rosa/hosted-cp/rosa-hcp-provision/0.2/rosa-hcp-provision.yaml

https://issues.redhat.com/browse/KONFLUX-5833
* added a cluster health check command to ROSA provision Task that is requesting health check status from OCM API - it succeeds when `health_state: "healthy"`
* updated `check_clusteroperators` function to not wait for all operators to be `progressing: false`, because according to the latest cluster provisioning failures this command seems to get stuck and we don't get any helpful outputs from it - instead we now rely on the `check_cluster_health_endpoint` function that also outputs the state of clusteroperators (in case the cluster health is not yet reported as `healthy`
* updated all 3 "versions" of the Task
* validated in https://github.com/konflux-ci/e2e-tests/pull/1523
* log from the cluster provision is archived …

feat: ROSA cluster health check

---

common/tasks/test-metadata/0.2/test-metadata.yaml

For push event type the JOB_SPEC git [values](https://github.com/konflux-ci/tekton-integration-catalog/blob/main/common/tasks/test-metadata/0.2/test-metadata.yaml#L82) `"pull_request_number": ,` generated by test-metadata does not have even empty value, which leads jq command to error out with error:
```
GIT_REPO="$(jq -r '.git.repo // empty' <<< $JOB_SPEC)"
jq: parse error: Expected value before ',' at line 6, column 32
```
**JOB_SPEC:**
```json
{                                         
"container_image": "quay.io/rhtap/rhtap-cli@sha256:f4f055b2a980445df8d1606ae777e543f2f7b65e973371d2f1823d4efcd6bf00",
"konflux_component": "rhtap-cli",
"snapshot": {"application":"rhtap-cli","components":[{"name":"rhtap-cli","containerImage":"quay.io/rhtap/rhtap-cli@sha256:f4f055b2a980445df8d1606ae777e543 …
```

Fix jq error for push event type

---

stepactions/bundles/pick-cluster-version/0.1/README.MD
stepactions/bundles/pick-cluster-version/0.1/pick-cluster-version.yaml

This StepAction selects a cluster version for provisioning. It determines the target OCP version of an FBC fragment. 
The version is returned if it is included in the list of supported Hypershift cluster versions.

feat(CVP-4398) Create a new step to pick cluster version

---

konflux/sealights-agents/go/Dockerfile
konflux/sealights-agents/nodejs/Dockerfile
konflux/sealights-agents/python/Dockerfile
renovate.json

https://issues.redhat.com/browse/KFLUXDP-208
Adding a version of the agent/CLI to the Dockerfile's env var will make it easier to pass it to the Tekton Results (which will be done in a follow-up PR)
```
➜  tekton-integration-catalog git:(KFLUXDP-208) podman build -q --platform linux/arm64 -t test-nodejsagent . -f konflux/sealights-agents/nodejs/Dockerfile && \
podman run -it test-nodejsagent /bin/bash -c 'echo -e "\nAGENT VERSION: $AGENT_VERSION"'
107c17fa63aa35f7a0bb2340377d2f38572e1fed6fbd2e27e32e74c077002e85
AGENT VERSION: 6.1.1006
```

feat: add SL agent/cli versions to env vars

---

stepactions/bundles/get-unreleased-bundle/0.1/README.MD
stepactions/bundles/get-unreleased-bundle/0.1/get-unreleased-bundle.yaml

This step retrieves the highest bundle version from a specified package and channel in a FBC fragment, then it verifies if this bundle is unreleased.
If the bundle is unreleased, the step returns it.
This step will be used by the "deploy-fbc" pipeline.

feat(CVP-4397) Create a new step to verify the bundle is unreleased

---

stepactions/gather-cluster-resources/0.1/README.md
stepactions/gather-cluster-resources/0.1/gather-cluster-resources.yaml

Add the stepaction to gather the cluster resources by running the gather-extra.sh script and give the user the possibility to run a script of their own that gathers resources that matter to their team.

KFLUXDP-159: Add stepaction to gather cluster resources

---

stepactions/sealights/create-test-session/0.1/README.md
stepactions/sealights/create-test-session/0.1/create-test-session.yaml
stepactions/sealights/upload-ginkgo-results/0.1/README.md
stepactions/sealights/upload-ginkgo-results/0.1/upload-ginkgo-results.yaml

There is a recommendation from Sealights to initialize the test session before we are executing the tests:
This Pull contain the following:
1. Dont create a session id if another one is comming in the params
2. Creates a trap to to delete always the session if already exists
3. Add a step action to initialize the test session separatelly

feat: StepAction receive a new test session id and not create one directly

---

README.md
pipelines/deploy-fbc-operator/0.1/README.MD
pipelines/deploy-fbc-operator/0.1/deploy-fbc-operator.yaml

Note: the reason I'm using an inline script for the install-operator step is to workaround the issue of not being able to use workspaces in an integration pipeline: https://issues.redhat.com/browse/STONEINTG-1089
Slack thread: https://redhat-internal.slack.com/archives/C030SGP2VB9/p1743086568464209
Once STONEINTG-1089 is implemented I can modify an already existing install-operator step to use workspaces and reference it in the pipeline with `ref`: https://github.com/konflux-ci/tekton-integration-catalog/tree/main/stepactions/bundles/install-operator/0.1

feat(CVP-4402): Add deploy-operator pipeline

---

pipelines/deploy-fbc-operator/0.1/deploy-fbc-operator.yaml
stepactions/bundles/install-operator/0.1/README.MD
stepactions/bundles/pick-cluster-arch/0.1/pick-cluster-arch.yaml
stepactions/bundles/pick-cluster-version/0.1/README.MD
stepactions/bundles/pick-cluster-version/0.1/pick-cluster-version.yaml

Improving a few things in the `deploy-fbc-operator` pipeline.
-  If neither arm64 nor amd64 is supported, exit with code 0 as a no-op
- If a product team adds an ITS for a 4.18+ component,  exit with code 0 as a no-op (Hypershift currently supports 4.14–4.17.)

fix: change return codes

---

pipelines/deploy-fbc-operator/0.1/deploy-fbc-operator.yaml

* Changed the original command from `curl -sfL "${mirror_set_url}"` to `curl -kfL "${mirror_set_url}"` so that it works on a private Konflux cluster.
* Fixed image mirror set file parsing: instead of always using the first mirror, the script now checks if the original image is pullable; if not, it traverses the mirrors one by one until a pullable one is found.
* Added a `|| "$INSTALL_NAMESPACE" == null` check, related to this PR: https://github.com/konflux-ci/konflux-test/pull/410.

feat(CLOUDDST-27015): Fix curl to work in a private Konflux clusters

---

common/tasks/quality-dashboard/0.1/quality-dashboard-upload.yaml

This Pull Request add the next logic:
* In case if the PipelineRun got cancelled by integration service then dont send any data to Quality Dashboard
* Send data to Quality Dashboard when Junit dont exist

feat:(KONFLUX-6588): send data to quality dashboard even when fail and there is no junit

---

pipelines/deploy-fbc-operator/0.1/README.MD
pipelines/deploy-fbc-operator/0.1/deploy-fbc-operator.yaml
stepactions/bundles/get-unreleased-bundle/0.1/get-unreleased-bundle.yaml
stepactions/bundles/install-operator/0.1/install-operator.yaml

1. Added support for accessing private GitHub and GitLab repositories.
General improvements:
- Added code to check if any mirrors exist for the image before iterating through them.
- Added the -n flag to the echo command when returning the package and channel name to remove the trailing newline.
- In the install-operator StepAction, incorporated changes that were previously introduced in the inline script within the pipeline to ensure consistency between both implementations.

feat(CLOUDDST-27042): Add support for private source code repos

---

konflux/sealights-agents/go/Dockerfile

```
error: error loading program packages: err: exit status 1: stderr: go: go.mod requires go >= 1.23.4 (running go 1.22.9; GOTOOLCHAIN=local)
```
This will fix an error during the scanning of Go projects with go version 1.23.X >.

Update Dockerfile to work with latest go version

---

common/tasks/pull-request-comment/0.1/pull-request-comment.yaml
common/tasks/pull-request-comment/0.2/pull-request-comment.yaml
common/tasks/quality-dashboard/0.1/quality-dashboard-upload.yaml
tasks/pull-request-comment/0.1/pull-request-comment.yaml
tasks/pull-request-comment/0.2/pull-request-comment.yaml

https://issues.redhat.com/browse/KONFLUX-7962
tested with this PR: https://github.com/konflux-ci/e2e-tests/pull/1582

fix: don't comment on PR if Pipeline is cancelled

---

pipelines/deploy-fbc-operator/0.1/deploy-fbc-operator.yaml
stepactions/bundles/install-operator/0.1/install-operator.yaml

1. Using a new konflux-test function resolve_to_0th_manifest_digest to change the digest of the FBC image 
2. Saving artifacts from CRDs creation before failing, to make debugging easier. We do the same in CVP so I'm re-using the code from here: https://github.com/openshift/release/blob/master/ci-operator/step-registry/optional-operators/subscribe/optional-operators-subscribe-commands.sh#L441
Please note: I'm duplicating the same in the install-operator step action that is currently used as an inline script in the pipeline due to the integration service limitations.

feat(CLOUDDST-27082): resolve FBC image to 0th manifest digest

---

scripts/rosa/delete-rosa-clusters.sh

Fixes the issue with deleting load balancers:
```
[INFO] Removing tag '2ipj1c2v48onihdgmkntbujvbfn84vmt' from subnets [...]...
./scripts/rosa/delete-rosa-clusters.sh: line 96: gdate: command not found
```
This is probably a remainder from my local testing 🍏  🙀

fix: rosa deletion script gdate -> date

---

pipelines/deploy-fbc-operator/0.1/deploy-fbc-operator.yaml

sometimes the step is failing with:
`"step-get-unreleased-bundle" exited with code 137`

fix(KONFLUX-8367): Increase get-unreleased-bundle resources

---

pipelines/deploy-fbc-operator/0.1/README.MD
pipelines/deploy-fbc-operator/0.1/deploy-fbc-operator.yaml

• Refactored the process-image-mirror-set step by moving a significant portion into a new task, fetch-image-mirror-set, to allow saving its result and passing it as a parameter to the create-cluster step.
• Providing the imageContentSources parameter to the create-cluster step enables applying IDMS on a running cluster:
https://github.com/konflux-ci/build-definitions/blob/main/stepactions/eaas-create-ephemeral-cluster-hypershift-aws/0.1/eaas-create-ephemeral-cluster-hypershift-aws.yaml#L35
• With these changes, deployment now succeeds without image pull errors.

fix(CLOUDDST-27427): apply IDMS on a running cluster

---

tasks/konflux-ci/deploy/0.1/Readme.md
tasks/konflux-ci/deploy/0.1/deploy-konflux-ci.yaml

https://issues.redhat.com/browse/KFLUXDP-290
Added a new step to the the deploy-konflux Task to solve PR pairing for release-service-catalog component
This change also required a new parameter `component-pr-source-branch` that has been added and documented

fix: PR pairing for release-service-catalog

---

tasks/mapt-oci/kind-aws-spot/provision/0.1/Readme.md
tasks/mapt-oci/kind-aws-spot/provision/0.1/kind-aws-provision.yaml

Soemtimes if Konflux infra fail for n outage reasons we should use mapt serverless to delete the remaining resources.

feat: Auto destroy AWS stacks after 2h by default

---

tasks/mapt-oci/kind-aws-spot/provision/0.1/Readme.md
tasks/mapt-oci/kind-aws-spot/provision/0.1/kind-aws-provision.yaml

Reverts konflux-ci/tekton-integration-catalog#171

Revert "feat: Auto destroy AWS stacks after 2h by default"

---

tasks/konflux-ci/deploy/0.2/deploy-konflux-ci.yaml
tasks/mapt-oci/kind-aws-spot/deprovision/0.1/kind-aws-deprovision.yaml
tasks/mapt-oci/kind-aws-spot/provision/0.1/kind-aws-provision.yaml
tasks/mapt-oci/kind-aws-spot/provision/0.2/Readme.md
tasks/mapt-oci/kind-aws-spot/provision/0.2/kind-aws-provision.yaml

This PR fixes a couple of things:
* revert timeout value to empty string in kind-aws-provision Task
* bump version of mapt to v0.9.2 (fixes issue with logging kubeconfig to the output)

fix: link solve-pr-pairing script in v0.2

---

tasks/mapt-oci/kind-aws-spot/deprovision/0.1/kind-aws-deprovision.yaml
tasks/mapt-oci/kind-aws-spot/provision/0.2/Readme.md
tasks/mapt-oci/kind-aws-spot/provision/0.2/kind-aws-provision.yaml

This PR updates the kind-aws-provision task to always create the kubeconfig secret at the very beginning of the Task execution. Previously, the secret was only created if the cluster was successfully provisioned, which could cause issues during cleanup if provisioning cancelled/failed early.

fix: create the kubeconfig secret at the begining of the provision task 

---

tasks/sealights/sealights-get-refs/0.1/sealights-get-refs.yaml

Fixes this issue when there's more than one task that matches the selector, which results multiple image refs printed out:
```
➜  /tmp jq -r '
.payload
| @base64d
| fromjson
| .predicate.buildConfig.tasks[]
| select(.invocation.parameters.IMAGE? // "" | test("sealights"))
| .invocation.parameters.IMAGE
' cosign_metadata.json
quay.io/rhdh/rhdh-hub-rhel9-sealights:1cd6092b9d79f36769cc8762b583cf6fea45d732
quay.io/rhdh/rhdh-hub-rhel9-sealights:1cd6092b9d79f36769cc8762b583cf6fea45d732
```

fix: sealights get ref: return only single match

---

tasks/konflux-ci/deploy/0.3/deploy-konflux-ci.yaml
tasks/mapt-oci/kind-aws-spot/provision/0.2/Readme.md
tasks/mapt-oci/kind-aws-spot/provision/0.2/kind-aws-provision.yaml

* update mapt version that supports exposing additional port (for PaC)
* update konflux-ci-deploy task to
* update deployment of konflux-ci to replace localhost with mapt kind cluster's public IP so it's publicly accessible
* add required pipelines-runner cluster role
* add kyverno policy for reducing CPU/Memory requests for E2E PLR pods
testing this change with https://github.com/konflux-ci/build-service/pull/448

feat: prepare for build/integration e2e tests

---

tasks/mapt-oci/kind-aws-spot/provision/0.2/kind-aws-provision.yaml

Fixes this issue when `extra-port-mappings` param is not specified:
```
/tekton/scripts/script-1-72jvl: line 17: conditional binary operator expected
```

fix: extra-ports param empty value condition

---

tasks/test-metadata/0.3/MIGRATION.md
tasks/test-metadata/0.3/README.md
tasks/test-metadata/0.3/test-metadata.yaml

Adds test-metadata v0.3 that combines functionality from v0.1 and v0.2 with new container parsing capabilities.
Key additions:
* Individual results (v0.1) + consolidated job-spec (v0.2)
* Prefetch artifacts (CACHI2 and SOURCE) from build container
* Container repository and tag extraction
* Enhanced error handling and logging

Add test-metadata v0.3 with enhanced functionality and container parsing

---

scripts/konflux-ci-deploy/solve-pr-pairing.sh
tasks/konflux-ci/deploy/0.3/deploy-konflux-ci.yaml

[previous PR](https://github.com/konflux-ci/tekton-integration-catalog/pull/198) fixed the pairing script for periodic jobs for release-service, but caused an issue in other konflux-ci components
those component shouldn't use pairing script but rather use [test-metadata v0.3](https://github.com/konflux-ci/tekton-integration-catalog/tree/main/tasks/test-metadata/0.3) which generates all required data
This PR also passes $EVENT_TYPE env var to the pr-pairing to determine the container image tag based on the push/pull event.
It also fixes an issue where the IMAGE_TAG extracted from the sealights-ref Task was overriden in the pr-pairing script which led to the test deploying an image which did not contain sealights instrumentation

fix: keep pairing only for "release" components

---

tasks/sealights/sealights-get-refs/0.1/sealights-get-refs.yaml

This PR fixes an issue when the build pipeline contains the multiarch build Task, which is not supported by sealights-get-refs Task, i.e. the sealights image extraction does not work and in that case and the image extraction falls back to the container image from the snapshot.
But since the image ref format extracted from the snapshot is 
`quay.io/<org>/<repo>sha256:<sha256-value>` and not 
`quay.io/<org>/<repo>:<tag>@sha256:<sha256-value>`
like it is expected [here](https://github.com/konflux-ci/tekton-integration-catalog/blob/822c22bf876294ff71f3f7d7dd2ededd6050a35a/tasks/sealights/sealights-get-refs/0.1/sealights-get-refs.yaml#L123), the container image tag is evaluated wrong and results in this value of image tag:
So this PR extracts the container image ref in expected format …

fix: container image ref format

---

tasks/konflux-ci/deploy/0.3/Readme.md

fixes version string in the readme of the version-3 `deploy-konflux-ci` task, from `0.2` to `0.3`.

docs: amend version in deploy-konflux-ci readme

---

scripts/konflux-ci-deploy/solve-pr-pairing.sh
tasks/konflux-ci/deploy/0.3/deploy-konflux-ci.yaml

Handles cases when PR is created from upstream repository branches (i.e. branches created by *[bot])
Tested in [this PR](https://github.com/konflux-ci/build-service/pull/468)

fix: deploy-konflux: dependabot PRs

---

tasks/pull-request-comment/0.1/README.md
tasks/pull-request-comment/0.1/pull-request-comment.yaml
tasks/pull-request-comment/0.2/README.md
tasks/pull-request-comment/0.2/pull-request-comment.yaml

Update pull-request-comment Task to add a link to the OCI artifact browser with the path to the related OCI artifact. After konflux-ci pipeline fails, a link to the artifact browser is added to the PR comment that will redirect user to the correct artifact.

feat: add OCI artifact viewer

---

tasks/mapt-oci/kind-aws-spot/deprovision/0.1/kind-aws-deprovision.yaml
tasks/mapt-oci/kind-aws-spot/provision/0.1/kind-aws-provision.yaml
tasks/mapt-oci/kind-aws-spot/provision/0.2/kind-aws-provision.yaml

* bump version of mapt to v0.9.7
* add `spot-eviction-tolerance` param
* fix logging issue
verified with
* https://github.com/konflux-ci/e2e-tests/pull/1656/commits/aff3f87d6b75862f12706a50158774ee3fbf06a6
* https://github.com/konflux-ci/image-controller/pull/213/commits/4e1f4195640815c40999e1902a3487fb024b0e5d#diff-642a5657e437b7abe9d81849a1ec198ee32c73420ab078e75ed87f9c4158af1aR88

fix: bump mapt version, fix provision task logging

---

tasks/linters/checkton/0.1/README.md
tasks/linters/checkton/0.1/checkton.yaml

The integration service is now using Checkton to test code changes. Since shellcheck is also stored in tekton-integration-catalog and checkton fulfills a similar purpose, it makes sense to also include Checkton in the catalog

feat: add Checkton tekton task to linting tasks

---

pipelines/deploy-fbc-operator/0.1/deploy-fbc-operator.yaml

There is a bug in the mirror lookup logic:
- The script tries to find the upstream image by checking whether the current BUNDLE_IMAGE appeared in the values of the mirror map (.value[]). But BUNDLE_IMAGE was always the upstream (a key in the map), not a mirror.
As a result, the lookup always failed with:
`No upstream mirror found for registry.redhat.io/... in mirror map.`
Slack thread: https://redhat-internal.slack.com/archives/C04PZ7H0VA8/p1756302636361019
IDMS: https://github.com/openshift/lightspeed-operator/blob/main/config/manager/imagedigestmirrorset.yaml
Testing output:
```
Could not inspect original pullspec registry.redhat.io/openshift-lightspeed/lightspeed-operator-bundle@sha256:e546394316e9dc745442894482fd233f31b3bb64260dabd2204c56ccc08d1274. Checking if there's a mirror …
```

fix(KONFLUX-9907): fix mirror lookup logic

---

tasks/linters/checkton/0.1/README.md
tasks/linters/checkton/0.1/checkton.yaml

Looks like the checkton task was accidentally deleted in #217 .  This commit adds it back.  For reference, the original PR was #208

fix: re-introduce checkton task

---

scripts/gather-extra.sh

This PR includes imagerepositories in the artifacts after the test execution (if fails) to help debug failures.

fix: add imagerepositories also in artifacts
